### ISSUE TITLE
Resizable Cards for Better Navigation 

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#1631]
Have a slider that resizes cards when dragged left or right.

This would be good for when searching the home screen or a channel with lots of content.

```css
.card-row__scrollhouse .card {
width: var(--card-size-slider);
}
```
![image](https://user-images.githubusercontent.com/29914179/41538727-4bd785f0-734f-11e8-9f89-b3efe47cfaaf.png)

![smalllbry](https://user-images.githubusercontent.com/29914179/41542506-758a41f4-7358-11e8-9ba0-0bdb709634c4.gif)
