### ISSUE TITLE
Reduce Limit For Title and URL Length

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#1690]
Currently, there is a long limit for URL and title length, apparently **240 characters**.

I imagine this could start being **taxing** on the **blockchain** in the future? I see no reason for titles and URLs over **60 characters** and would help keep URLs and metadata looking clean. I guess it would also help prevent **malicious code** injections.

Also, long URLs **break** formatting in-app as shown in below image.

![image](https://user-images.githubusercontent.com/29914179/41890123-699859ea-7951-11e8-870a-c87fa51bd4a9.png)

![image](https://user-images.githubusercontent.com/29914179/41890171-a2fa3d70-7951-11e8-863a-68d3b100a77e.png)

![image](https://user-images.githubusercontent.com/29914179/41890146-880877b6-7951-11e8-8a0f-a59013046b4b.png)

![image](https://user-images.githubusercontent.com/29914179/41890723-18e68c1c-7954-11e8-8eab-55a8c5bbd550.png)

**Comment by Invariant-Change** [comment]
Formatting fix would look something like this, which tourniquets anything over the set length.

```css
span.btn__content p {
    width: 300px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
![image](https://user-images.githubusercontent.com/29914179/41891043-ce84d654-7955-11e8-84f7-c60087bed80e.png)

**Comment by tzarebczan** [comment]
Notice the fee? :p Longer claim names require a larger fee. I'm not sure if the app is the right place to set the limits, we can leave that up for discussion.

**Comment by Invariant-Change** [comment]
Yeah. Maybe a blockchain limitation would be better!

App formatting needs fixing though to cope with any titles longer than the width of the table.

@seanyesmunt 

I'm currently experimenting with ways to do this. Text fields are displayed as `<span>` but need to be a text element for this to work. If changed to a `<p>` the fix is easy and you get the below fitted content.

### CODE FIX
```css
span.btn__content p {
    width: 300px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
### NOT FIXED

![image](https://user-images.githubusercontent.com/29914179/41891565-592ebc00-7958-11e8-9048-d2c9312c4b2d.png)

### FIXED

![image](https://user-images.githubusercontent.com/29914179/41891448-cc9f78e2-7957-11e8-9029-ea6814baccd0.png)
