### ISSUE TITLE
Card & Thumbs Have Different Background Size Properties

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#1876]
The CSS for the cards and thumbs are diffrrent. This means that what people see in the thumb area isn't the same as what they will see in cards.

**Card: **

```css
.card__media {
    background-size: cover;
    background-repeat: no-repeat;
    background-position: 50% 50%;
    background-color: var(--color-placeholder);
}
```

**Thumb:**

```css
.thumbnail-preview {
    height: var(--thumbnail-preview-height);
    width: var(--thumbnail-preview-width);
    border: var(--thumbnail-preview-border);
}
```

![image](https://user-images.githubusercontent.com/29914179/44097767-e30f7384-a021-11e8-9909-1af921b97294.png)

![image](https://user-images.githubusercontent.com/29914179/44097786-ebf2d34c-a021-11e8-86de-d7bfe46e125a.png)

As another option, you could take out the size and width from the thumb and get the correct aspect ratio and contained in the css max height/width set area. However, this is not how it will look as a card unless the card CSS is the same.

```css
.thumbnail-preview {
    height: var(--thumbnail-preview-height);
    /* width: var(--thumbnail-preview-width); */
    /* border: var(--thumbnail-preview-border); */
}
```

![image](https://user-images.githubusercontent.com/29914179/44097931-3c493778-a022-11e8-92f7-c0a9b6cc5ad3.png)

*Took out the border for easier visualisation of this issue.
